#!/bin/bash
pkgname=filesystem
pkgver=0
pkgver_postfix=

pkg_prepare() {
    return
}

pkg_build() {
    return
}

pkg_check() {
    return
}

pkg_install() {
    mkdir -pv ${fakeroot_dir}/{dev,proc,sys,run}

    mkdir -pv ${fakeroot_dir}/{bin,boot,etc/{opt,sysconfig},home,lib,mnt,opt}
    mkdir -pv ${fakeroot_dir}/{media/{floppy,cdrom},sbin,srv,var}
    install -dv -m 0750 ${fakeroot_dir}/root
    install -dv -m 1777 ${fakeroot_dir}/tmp ${fakeroot_dir}/var/tmp
    mkdir -pv ${fakeroot_dir}/usr/{,local/}{bin,include,lib,sbin,src}
    mkdir -pv ${fakeroot_dir}/usr/{,local/}share/{color,dict,doc,info,locale,man}
    mkdir -v  ${fakeroot_dir}/usr/{,local/}share/{misc,terminfo,zoneinfo}
    mkdir -v  ${fakeroot_dir}/usr/libexec
    mkdir -pv ${fakeroot_dir}/usr/{,local/}share/man/man{1..8}

    case $(uname -m) in
         x86_64) ln -sv lib ${fakeroot_dir}/lib64     && 
                 ln -sv lib ${fakeroot_dir}/usr/lib64 && 
                 ln -sv lib ${fakeroot_dir}/usr/local/lib64 ;;
    esac

    mkdir -v ${fakeroot_dir}/var/{log,mail,spool}
    ln -sv /run ${fakeroot_dir}/var/run
    ln -sv /run/lock ${fakeroot_dir}/var/lock
    mkdir -pv ${fakeroot_dir}/var/{opt,cache,lib/{color,misc,locate},local}
}

pkg_postinstall() {
    mknod -m 600 ${install_prefix}/dev/console c 5 1
    mknod -m 666 ${install_prefix}/dev/null c 1 3
}

pkg_remove() {
    rm ${install_prefix}/dev/console
    rm ${install_prefix}/dev/null
}
