#!/bin/bash
pkgname=less
pkgver=458
pkgver_postfix=

sources=( "http://www.greenwoodsoftware.com/${pkgname}/${pkgname}-${pkgver}.tar.gz" )
sha1sums=( 'd5b07180d3dad327ccc8bc66818a31577e8710a2' )

lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}-${pkgver}.tar.gz" -C "$build_dir"

    cd "${build_dir}/${pkgname}-${pkgver}"

    ./configure --prefix=/usr --sysconfdir=/etc
}

lfs_me_check() {
    return
}
