#!/bin/bash
pkgname=less
pkgver=458
pkgver_postfix=

lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}-${pkgver}.tar.gz" -C "$build_dir"

    cd "${build_dir}/${pkgname}-${pkgver}"

    ./configure --prefix=/usr --sysconfdir=/etc
}

lfs_me_check() {
    return
}
