#!/bin/bash
pkgname=lfs-network-scripts
pkgver=20140214
pkgver_postfix=

lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}-${pkgver}.tar.bz2" -C "$build_dir"

    cd "${build_dir}/${pkgname}-${pkgver}"
}

lfs_me_build() {
    return
}

lfs_me_check() {
    return
}

lfs_me_install() {
    make DESTDIR="$fakeroot_dir" install
}
