#!/bin/bash
pkgname=systemd
pkgver=208
pkgver_postfix=

sources=( "http://www.freedesktop.org/software/${pkgname}/${pkgname}-${pkgver}.tar.xz" )
sha1sums=( 'e1a4e213d5d1e3498bca851347f2f07fdb9b4e1f' )

lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}-${pkgver}.tar.xz" -C "$build_dir"

    cd "${build_dir}/${pkgname}-${pkgver}"

    echo 'KILL=/bin/kill
    HAVE_BLKID=1
    BLKID_LIBS="-lblkid"
    BLKID_CFLAGS="-I/tools/include/blkid"' > config.cache
    sed -i -e 's/^\s*//' config.cache #remove whitespaces at beginning of lines

    sed -i "s:blkid/::" src/udev/udev-builtin-blkid.c

    ./configure --prefix=/usr                                \
                --sysconfdir=/etc                            \
                --localstatedir=/var                         \
                --docdir=/usr/share/doc/${pkgname}-${pkgver} \
                --config-cache                               \
                --with-rootprefix=                           \
                --with-rootlibdir=/lib                       \
                --enable-split-usr                           \
                --disable-gudev                              \
                --without-python
}

lfs_me_build() {
    make LIBRARY_PATH=/tools/lib
}

lfs_me_check() {
    sed -i s:test/udev-test.pl::g Makefile
    make check 2>&1 | tee "${current_dir}/${pkgname}-check-log"
}

lfs_me_install() {
    make DESTDIR="$fakeroot_dir" LD_LIBRARY_PATH=/tools/lib install

    for cat in 1 3 5 7 8
    do
        mkdir -pv "${fakeroot_dir}/usr/share/man/man${cat}"
          install -v -m644 man/*.${cat} "${fakeroot_dir}/usr/share/man/man${cat}"
    done

    mv -v "${fakeroot_dir}/usr/lib/libnss_myhostname.so.2" "${fakeroot_dir}/lib"

    rm -rfv "${fakeroot_dir}/usr/lib/rpm"

    mkdir -pv "${fakeroot_dir}/sbin"
    for tool in runlevel reboot shutdown poweroff halt telinit; do
         ln -sfv ../bin/systemctl "${fakeroot_dir}/sbin/${tool}"
    done
    ln -sfv ../lib/systemd/systemd "${fakeroot_dir}/sbin/init"

    sed -i "s@0775 root lock@0755 root root@g" "${fakeroot_dir}/usr/lib/tmpfiles.d/legacy.conf"
}

lfs_me_postinstall() {
    systemd-machine-id-setup
}

lfs_me_postremove() {
    rm /etc/machine-id
}
