#!/bin/bash
pkgname=bash-startup
pkgver=0
pkgver_postfix=

lfs_me_prepare() {
    cd "$build_dir"
}

lfs_me_build() {
    echo \
"# Begin /etc/profile
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>
# modifications by Dagmar d'Surreal <rivyqntzne@pbzpnfg.arg>

# System wide environment variables and startup programs.

# System wide aliases and functions should go in /etc/bashrc.  Personal
# environment variables and startup programs should go into
# ~/.bash_profile.  Personal aliases and functions should go into
# ~/.bashrc.

# Functions to help us manage paths.  Second argument is the name of the
# path variable to be modified (default: PATH)
pathremove () {
    local IFS=':'
    local NEWPATH
    local DIR
    local PATHVARIABLE=\${2:-PATH}
    for DIR in \${!PATHVARIABLE} ; do
        if [ \"\$DIR\" != \"\$1\" ] ; then
            NEWPATH=\${NEWPATH:+\$NEWPATH:}\$DIR
        fi
    done
    export \$PATHVARIABLE=\"\$NEWPATH\"
}

pathprepend () {
    pathremove \$1 \$2
    local PATHVARIABLE=\${2:-PATH}
    export \$PATHVARIABLE=\"\$1\${!PATHVARIABLE:+:\${!PATHVARIABLE}}\"
}

pathappend () {
    pathremove \$1 \$2
    local PATHVARIABLE=\${2:-PATH}
    export \$PATHVARIABLE=\"\${!PATHVARIABLE:+\${!PATHVARIABLE}:}\$1\"
}

export -f pathremove pathprepend pathappend

# Set the initial path
export PATH=/bin:/usr/bin

if [ \$EUID -eq 0 ] ; then
    pathappend /sbin:/usr/sbin
    unset HISTFILE
fi

# Setup some environment variables.
export HISTSIZE=1000
export HISTIGNORE=\"&:[bf]g:exit\"

# Set some defaults for graphical systems
export XDG_DATA_DIRS=/usr/share

# Setup a red prompt for root and a green one for users.
NORMAL=\"\\[\\e[0m\\]\"
RED=\"\\[\\e[1;31m\\]\"
GREEN=\"\\[\\e[1;32m\\]\"
if [[ \$EUID == 0 ]] ; then
    PS1=\"\$RED\\u [ \$NORMAL\\w\$RED ]# \$NORMAL\"
else
    PS1=\"\$GREEN\\u [ \$NORMAL\\w\$GREEN ]\\\$ \$NORMAL\"
fi

for script in /etc/profile.d/*.sh ; do
    if [ -r \$script ] ; then
        . \$script
    fi
done

# End /etc/profile" > profile

    echo \
"# Setup for /bin/ls and /bin/grep to support color, the alias is in /etc/bashrc.
if [ -f \"/etc/dircolors\" ] ; then
    eval \$(dircolors -b /etc/dircolors)

    if [ -f \"\$HOME/.dircolors\" ] ; then
        eval \$(dircolors -b \$HOME/.dircolors)
    fi
fi
alias ls='ls --color=auto'
alias grep='grep --color=auto'" > dircolors.sh

    echo \
"if [ -d /usr/local/lib/pkgconfig ] ; then
    pathappend /usr/local/lib/pkgconfig PKG_CONFIG_PATH
fi
if [ -d /usr/local/bin ]; then
    pathprepend /usr/local/bin
fi
if [ -d /usr/local/sbin -a \$EUID -eq 0 ]; then
    pathprepend /usr/local/sbin
fi

if [ -d ~/bin ]; then
    pathprepend ~/bin
fi
#if [ \$EUID -gt 99 ]; then
#        pathappend .
#fi" > extrapaths.sh

    echo \
"# Setup the INPUTRC environment variable.
if [ -z \"\$INPUTRC\" -a ! -f \"\$HOME/.inputrc\" ] ; then
    INPUTRC=/etc/inputrc
fi
export INPUTRC" > readline.sh

    echo \
"# By default, the umask should be set.
if [ \"\$(id -gn)\" = \"\$(id -un)\" -a \$EUID -gt 99 ] ; then
    umask 002
else
    umask 022
fi" > umask.sh

    echo \
"# Begin /etc/bashrc
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>
# updated by Bruce Dubbs <bdubbs@linuxfromscratch.org>

# System wide aliases and functions.

# System wide environment variables and startup programs should go into
# /etc/profile.  Personal environment variables and startup programs
# should go into ~/.bash_profile.  Personal aliases and functions should
# go into ~/.bashrc

# Provides colored /bin/ls and /bin/grep commands.  Used in conjunction
# with code in /etc/profile.

alias ls='ls --color=auto'
alias grep='grep --color=auto'

# Provides prompt for non-login shells, specifically shells started
# in the X environment. [Review the LFS archive thread titled
# PS1 Environment Variable for a great case study behind this script
# addendum.]

NORMAL=\"\\[\\e[0m\\]\"
RED=\"\\[\\e[1;31m\\]\"
GREEN=\"\\[\\e[1;32m\\]\"
if [[ \$EUID == 0 ]] ; then
    PS1=\"\$RED\\u [ \$NORMAL\\w\$RED ]# \$NORMAL\"
else
    PS1=\"\$GREEN\\u [ \$NORMAL\\w\$GREEN ]\\\$ \$NORMAL\"
fi

# End /etc/bashrc" > bashrc


    echo \
"# Begin ~/.bash_profile
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>
# updated by Bruce Dubbs <bdubbs@linuxfromscratch.org>

# Personal environment variables and startup programs.

# Personal aliases and functions should go in ~/.bashrc.  System wide
# environment variables and startup programs are in /etc/profile.
# System wide aliases and functions are in /etc/bashrc.

append () {
    # First remove the directory
    local IFS=':'
    local NEWPATH
    for DIR in \$PATH; do
        if [ \"\$DIR\" != \"\$1\" ]; then
            NEWPATH=\${NEWPATH:+\$NEWPATH:}\$DIR
        fi
    done

    # Then append the directory
    export PATH=\$NEWPATH:\$1
}

if [ -f \"\$HOME/.bashrc\" ] ; then
    source \$HOME/.bashrc
fi

if [ -d \"\$HOME/bin\" ] ; then
    append \$HOME/bin
fi

unset append

# End ~/.bash_profile" > .bash_profile

    echo \
"# Begin ~/.bashrc
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>

# Personal aliases and functions.

# Personal environment variables and startup programs should go in
# ~/.bash_profile.  System wide environment variables and startup
# programs are in /etc/profile.  System wide aliases and functions are
# in /etc/bashrc.

if [ -f \"/etc/bashrc\" ] ; then
    source /etc/bashrc
fi

# End ~/.bashrc" > .bashrc



    echo \
"# Begin ~/.bash_logout
# Written for Beyond Linux From Scratch
# by James Robertson <jameswrobertson@earthlink.net>

# Personal items to perform on logout.

# End ~/.bash_logout" > .bash_logout

    dircolors -p > dircolors
}

lfs_me_check() {
    return
}

lfs_me_install() {
    mkdir -pv "${fakeroot_dir}/etc/skel"
    mkdir -pv "${fakeroot_dir}/etc/profile.d"

    mv profile bashrc dircolors "${fakeroot_dir}/etc/"
    mv dircolors.sh extrapaths.sh readline.sh umask.sh "${fakeroot_dir}/etc/profile.d/"
    mv .bash_profile .bashrc .bash_logout "${fakeroot_dir}/etc/skel"
}
