#!/bin/bash
pkgname=wireless_tools
pkgver=29
pkgver_postfix=

sources=( "http://www.hpl.hp.com/personal/Jean_Tourrilhes/Linux/${pkgname}.${pkgver}.tar.gz" )
sha1sums=( '22040ac1497f4c5f8ddeca365591b01ae3475710' )

lfs_me_prepare() {
    tar -xf "${sources_dir}/${pkgname}.${pkgver}.tar.gz" -C "$build_dir"

    cd "${build_dir}/${pkgname}.${pkgver}"
}

lfs_me_check() {
    return
}

lfs_me_install() {
    make PREFIX="${fakeroot_dir}/usr" INSTALL_MAN="${fakeroot_dir}/usr/share/man" install
}
